In [1]:
import numpy as np
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target == 9] = 1
y[digits.target != 9] = 0

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 666)

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

y_predict = log_reg.predict(X_test)

#混淆矩阵
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_predict))

#精准率
from sklearn.metrics import precision_score
print(precision_score(y_test, y_predict))

#召回率
from sklearn.metrics import recall_score
print(recall_score(y_test, y_predict))

f:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[403   2]
 [  9  36]]
0.9473684210526315
0.8


In [6]:
print(log_reg.decision_function(X_test)[:10]) #默认以0为分界线
print(log_reg.predict(X_test)[:10]) #由于前10都为负数，因此预测为0

[-22.05693891 -33.02936548 -16.21330861 -80.37912222 -48.2511933
 -24.5400128  -44.39160831 -25.04291356  -0.97823105 -19.71741038]
[0 0 0 0 0 0 0 0 0 0]


In [7]:
decision_score = log_reg.decision_function(X_test)
print(np.min(decision_score))
print(np.max(decision_score))

-85.68606427381654
19.889667515433775


#### 改变分类判断的阈值

In [8]:
y_predict2 = np.array(decision_score >= 5, dtype = 'int') #设置阈值为5

In [10]:
#混淆矩阵
print(confusion_matrix(y_test, y_predict2))
#精准率
print(precision_score(y_test, y_predict2))
#召回率
print(recall_score(y_test, y_predict2))

[[404   1]
 [ 21  24]]
0.96
0.5333333333333333


In [12]:
 #设置阈值为-5
y_predict3 = np.array(decision_score >= -5, dtype = 'int')
#混淆矩阵
print(confusion_matrix(y_test, y_predict3))
#精准率
print(precision_score(y_test, y_predict3))
#召回率
print(recall_score(y_test, y_predict3))

[[390  15]
 [  5  40]]
0.7272727272727273
0.8888888888888888
