In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [3]:
x.shape

(150, 4)

In [4]:
y.shape

(150,)

## train_test_split

In [5]:
shuffle_indexes = np.random.permutation(len(x)) #进行索引乱序处理
shuffle_indexes

array([102,  10,  90, 147,  30,  69,  36,  82, 132, 128, 149, 115, 124,
       110,   9,  78,  16,  87,  51,  76, 145, 122,  27,  73,  61, 141,
       137, 139,  50,  71,   1,  74, 133,   8,  48, 116,  84,  41, 108,
       109, 146, 123, 126, 104,  21,  14,  28,   6,  91, 105, 113,  35,
        97,  32, 112,  13,  81,  86, 130,  31,  63,  94,   2,  75,  54,
        72,  11,  17,  40,  60,  67, 100, 142,  85, 140, 101, 120, 118,
         4,  22, 125,  55,  77,  57,   3,  65,  95,  96, 107,  83, 129,
        24,  20, 136,  70, 138,  68,  23,  80,  38,  62,   5,  26,  34,
        89,  44,  98,  29, 148,  93,  79,  47,  53,  45,  99,  46, 131,
        56,  49,  19, 127, 117, 111, 106,  88,  18,  42,  37,  64,  12,
       134, 114,  92,  15,  58,  39,  59, 143,  25, 103,   0,  66, 121,
       119, 135, 144,  43,   7,  52,  33])

In [6]:
test_ratio = 0.2 #测试用例比例
test_size = int(len(x) * test_ratio) #测试的个数
test_indexes = shuffle_indexes[:test_size] #测试的数据
train_indexes = shuffle_indexes[test_size:] #训练数据集

In [7]:
X_train = x[train_indexes]
y_train = y[train_indexes]

X_test = x[test_indexes]
y_test = y[test_indexes]

In [8]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


## 使用实现的方法测试数据

In [10]:
from model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, seed = 666)


In [13]:
from kNN import KNNClassifier

In [14]:
knn = KNNClassifier(6)

In [15]:
knn.fit(X_train, y_train)

设置的KNN(k = 6)

In [22]:
y_predict = knn.predict(X_test)

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [21]:
from metrics import root_mean_squared_error
root_mean_squared_error(y_predict, y_test)

0.0

## sklearn中的train_test_split

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state = 666) #random是随机种子
X_train.shape

(120, 4)

In [63]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(6)
knn.fit(X_train, y_train)
y_predict = knn.predict(X_test)
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [64]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [66]:
from sklearn.metrics import r2_score
r2_score(y_test, y_predict)

1.0